// Auto-generated: file → real internal family name for bundled Hebrew fonts.
// Source: fc-query on /opt/cool/systemplate/usr/share/fonts/truetype/velr-hebrew/*.
export const HEBREW_FONT_FILE_TO_FAMILY: Record<string, string> = {
  "885f1e14-4070-4fdb-b7f2-9e446c5942d3_ravendafree.ttf": "Ravenda",
  "AnyConv.com__eft_frankfurt-webfont.ttf": "EFT_Frankfurt",
  "BAWS-Esthetic-Bold.ttf": "BAWS Esthetic",
  "BAWS-Esthetic-Decor.ttf": "BAWS Esthetic",
  "BAWS-Esthetic-Light.ttf": "BAWS Esthetic",
  "BAWS-Esthetic-Regular.ttf": "BAWS Esthetic",
  "BAWS-HaYetzira-Decor.ttf": "BAWS HaYetzira",
  "BAWS-HaYetzira-Rolltext-II.ttf": "BAWS HaYetzira",
  "BAWS-HaYetzira-Rolltext.ttf": "BAWS HaYetzira",
  "BAWS-Nostalgia-Old.ttf": "BAWS Nostalgia",
  "BAWS-Yoel-Bold.ttf": "BAWS Yoel",
  "BAWSCampeiner-Regular.ttf": "BAWS Campeiner",
  "EFT_Classic": "EFT_Classic",
  "EFT_Graphologya.ttf": "EFT_Graphologya",
  "EFT_Tehilot-webfont.ttf": "EFT_Tehilot",
  "FbFrankReal.ttf": "FbFrankReal",
  "FbFrankRealBold.ttf": "FbFrankReal",
  "FbFrankRealLight.ttf": "FbFrankReal Light",
  "FbwDavid.otf": "FontbitDavid",
  "FbwDavid.ttf": "SR_FontbitDavid",
  "FbwDavidBold.otf": "FontbitDavid",
  "FbwDavidBold.ttf": "SR_FontbitDavid",
  "MiriamCLM-Book.ttf": "Miriam CLM",
  "david.ttf": "David",
  "davidbd.ttf": "David",
  "eft_atara-webfont1.ttf": "EFT_Atara",
  "eft_avukado-webfont.ttf": "EFT_Avukado",
  "eft_hahozvimwebfont.ttf": "EFT_Hahozvim",
  "eft_hebrewwebfont.ttf": "EFT_Hebrew",
  "eft_hipstar_ot-webfont.ttf": "EFT_HIPSTAR",
  "eft_icecoffie-webfont.ttf": "EFT_IceCoffie",
  "eft_judaicaotswebfont.ttf": "EFT_Judaica",
  "eft_kdilak_sans-webfont.ttf": "EFT_Kdilak Sans",
  "eft_kita_alef-webfont.ttf": "EFT_Kita Alef",
  "eft_kitabet-webfont.ttf": "EFT_KitaBet",
  "eft_kiyosk_heavy_ot-webfont.ttf": "EFT_kiyosk Heavy",
  "eft_kroasonwebfont.ttf": "EFT_Kroason",
  "eft_kulmuswebfont.ttf": "EFT_Kulmus",
  "eft_labirintwebfont.ttf": "EFT_Labirint",
  "eft_legioner-webfont.ttf": "EFT_Legioner",
  "eft_lemonade-webfont.ttf": "EFT_Lemonade",
  "eft_litufwebfont.ttf": "EFT_Lituf",
  "eft_maplewebfont.ttf": "EFT_Maple",
  "eft_marshmelo-webfont.ttf": "EFT_Marshmelo",
  "eft_mashat-webfont.ttf": "EFT_Mashat",
  "eft_matcon-webfont.ttf": "EFT_Matcon",
  "eft_mesora-webfont.ttf": "EFT_Mesora",
  "eft_miriam_elagean-webfont.ttf": "EFT_Miriam Elagean",
  "eft_nefesh-webfont_Liran.ttf": "EFT_Nefesh",
  "eft_neon_full-webfont1.ttf": "EFT_Neon Full",
  "eft_netsach_neria-webfont1.ttf": "EFT_Netsach Neria",
  "eft_newletter_elegant-webfont.ttf": "EFT_NewLetter Elegant",
  "eft_noyvirt_peleot-webfont.ttf": "EFT_Noyvirt PeleOT",
  "eft_office-webfont_Liran.ttf": "EFT_Office",
  "eft_offset-webfont.ttf": "EFT_OffSet",
  "eft_olehadashwebfont.ttf": "EFT_OleHadash",
  "eft_paalul-webfont.ttf": "EFT_Paalul",
  "eft_paamonim_otswebfont.ttf": "EFT_Paamonim",
  "eft_pascal-webfont.ttf": "EFT_Pascal",
  "eft_patientwebfont.ttf": "EFT_Patient",
  "eft_patpetet-webfont.ttf": "EFT_Patpetet",
  "eft_pegasus-webfont.ttf": "EFT_Pegasus",
  "eft_pilpelharif-webfont.ttf": "EFT_PilpelHarif",
  "eft_pilpilon-webfont.ttf": "EFT_Pilpilon",
  "eft_plastica-webfont.ttf": "EFT_Plastica",
  "eft_pnina-webfont.ttf": "EFT_Pnina",
  "eft_pnina_decor-webfont.ttf": "EFT_Pnina Decor",
  "eft_prehistoric-webfont.ttf": "EFT_PreHistoric",
  "eft_primaries-webfont.ttf": "EFT_Primarie",
  "eft_progtextgold-webfont.ttf": "EFT_ProgtextGold",
  "eft_raashanwebfont.ttf": "EFT_Raashan",
  "eft_rashi_ot-webfont.ttf": "EFT_Rashi",
  "eft_regga-webfont2.ttf": "EFT_Regga",
  "eft_resisimwebfont.ttf": "EFT_Resisim",
  "eft_sabress-webfont.ttf": "EFT_Sabress",
  "eft_shaareyzedek_ot-webfont.ttf": "EFT_ShaareyZedek",
  "eft_shaashuim_ot-webfont.ttf": "EFT_Shaashuim",
  "eft_sharvit-webfont.ttf": "EFT_Sharvit",
  "eft_shifnuk-webfont.ttf": "EFT_Shifnuk",
  "eft_shukon-webfont.ttf": "EFT_Shukon",
  "eft_sicumim-webfont.ttf": "EFT_Sicumim",
  "eft_sifrut_open_otpwebfont.ttf": "EFT_Sifrut Open",
  "eft_sifrut_otpwebfont.ttf": "EFT_Sifrut",
  "eft_sinaimitkiwebfont.ttf": "EFT_SinaiMitki",
  "eft_skup-webfont.ttf": "EFT_Skup",
  "eft_stam_ari-webfont.ttf": "EFT_Stam Ari",
  "eft_stam_beityosef-webfont.ttf": "EFT_Stam BeitYosef",
  "eft_stam_sfaradi-webfont.ttf": "EFT_STAM SFARADI",
  "eft_stamsf_aradi_notag-webfont.ttf": "EFT_STAM SFARADI notag",
  "eft_studentit-webfont.ttf": "EFT_Studentit",
  "eft_sufatalim-webfont3.ttf": "EFT_SufatAlim",
  "eft_talpiot_class_regwebfont.ttf": "EFT_Talpiot Class",
  "eft_talpiot_regwebfont.ttf": "EFT_Talpiot",
  "eft_tamar-webfont.ttf": "EFT_Tamar",
  "eft_telescope-webfont.ttf": "EFT_Telescope",
  "eft_termus_ot-webfont.ttf": "EFT_TERMUS",
  "eft_textina-webfont.ttf": "EFT_Textina",
  "eft_textural-webfont-1.ttf": "EFT_Textural",
  "eft_tirosh_ot-webfont.ttf": "EFT_Tirosh",
  "eft_tsafon-webfont.ttf": "EFT_Tsafon",
  "eft_turbo_ot-webfont.ttf": "EFT_Turbo",
  "eft_yesodoteitanim-webfont.ttf": "EFT_YesodotEitanim",
  "eft_zarbuvit-webfont.ttf": "EFT_Zarbuvit",
  "eft_zarka-webfont-1.ttf": "EFT_Zarka",
  "eft_zecharya-webfont.ttf": "EFT_Zecharya",
  "eft_zrima-webfont.ttf": "EFT_Zrima",
  "frank.ttf": "FrankRuehl",
  "gisha.ttf": "Gisha",
  "gishabd.ttf": "Gisha",
  "pft_david-webfont.ttf": "PFT_David",
  "pft_dor-webfont.ttf": "PFT_Dor",
  "pft_frank-webfont.ttf": "PFT_Frank",
  "pft_hayimn-webfont.ttf": "PFT_Hayimn",
  "pft_ivri-webfont.ttf": "PFT_Ivri",
  "pft_ivri_bold-webfont.ttf": "PFT_Ivri",
  "pft_ivric-webfont.ttf": "PFT_Ivric",
  "pft_ktav-webfont.ttf": "PFT_Ktav",
  "pft_meiri-webfont.ttf": "PFT_Meiri",
  "pft_ophir-webfont.ttf": "PFT_Ophir",
  "pft_rashi-webfont2.ttf": "PFT_Rashi",
  "pft_sivan-webfont.ttf": "PFT_Sivan",
  "pft_stam-webfont.ttf": "PFT_Stam",
  "pft_vilna-webfont.ttf": "PFT_Vilna",
  "pft_yrushalmi-webfont.ttf": "PFT_Yrushalmi",
  "ABCDEE+lubavittch770.ttf": "lubavittch770",
  "FbwLivorna.otf": "FontbitLivorna",
  "FbwLivornaBold.otf": "FontbitLivorna",
  "LivornoBold.ttf": "NewLivornoMF",
  "lvnm.ttf": "Levenim MT",
  "lvnmbd.ttf": "Levenim MT",
  "nrkis.ttf": "Narkisim"
};
